# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-18 09:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainGDMS', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='tableNames',
            fields=[
                ('stringName', models.CharField(max_length=32, primary_key=True, serialize=False, unique=True)),
                ('dbName', models.CharField(max_length=32, unique=True)),
            ],
        ),
    ]
