# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-01-07 18:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainGDMS', '0003_auto_20180107_1610'),
    ]

    operations = [
        migrations.AddField(
            model_name='character',
            name='name',
            field=models.CharField(default='Character', max_length=64, unique=True),
            preserve_default=False,
        ),
    ]
